alter table exercises add column description text;

update exercises set description = 'Lie on a flat bench, grip the bar just wider than shoulder-width, and lower it to your mid-chest with elbows at roughly 45°. Drive it back up in a straight line. Keep your shoulder blades pinned and feet planted — don''t let the bar drift toward your face.' where name = 'Barbell Bench Press';
update exercises set description = 'Sit with back support, dumbbells at shoulder height, palms forward. Press straight overhead until arms are extended without locking out hard, then lower with control. Avoid arching your lower back to compensate — brace your core throughout.' where name = 'Seated Dumbbell Press';
update exercises set description = 'Stand at a cable machine with a straight or angled bar, elbows pinned to your sides. Extend your forearms down until arms are straight, squeezing the triceps at the bottom, then let the bar return slowly. Keep your elbows still — only the forearms move.' where name = 'Triceps Pushdown';
update exercises set description = 'Stand with feet hip-width, bar over mid-foot. Hinge down, grip just outside your legs, chest up and back flat. Drive through the floor with your legs, keeping the bar close to your body, and finish standing tall with hips through. Never round your lower back.' where name = 'Deadlift';
update exercises set description = 'Hinge forward from the hips to about 45°, bar hanging at arm''s length, back flat. Pull the bar toward your lower ribs, squeezing your shoulder blades together, then lower under control. Avoid using momentum or standing up between reps.' where name = 'Barbell Row';
update exercises set description = 'Stand with a shoulder-width grip, elbows tucked to your sides. Curl the bar up by bending only at the elbow, squeeze the biceps at the top, then lower slowly. Don''t swing your hips or let your elbows drift forward.' where name = 'Barbell Curl';
update exercises set description = 'Bar racked across your upper back, feet shoulder-width. Break at the hips and knees together, sitting down and back until thighs are at least parallel, then drive up through your whole foot. Keep your chest up and knees tracking over your toes.' where name = 'Back Squat';
update exercises set description = 'Sit in the machine with feet shoulder-width on the platform. Lower the weight until your knees reach about 90°, then press through your heels back to the start without locking your knees out hard. Don''t let your lower back round off the pad.' where name = 'Leg Press';
update exercises set description = 'Stand on the platform with the balls of your feet, heels hanging off the edge. Rise as high as you can onto your toes, pause briefly, then lower until you feel a deep stretch in your calves. Keep the movement slow and controlled — don''t bounce.' where name = 'Standing Calf Raise';
update exercises set description = 'Set the bench to a 30–45° incline. Lower the bar to your upper chest with elbows at roughly 45°, then press back up in a straight line. A steeper angle shifts more work to the front shoulders, so keep the incline moderate.' where name = 'Incline Bench Press';
update exercises set description = 'Grip the bar wider than shoulder-width, sit with thighs secured under the pad. Pull the bar down to your upper chest by driving your elbows down and back, then let it return under control. Avoid leaning back excessively or using your body weight to yank it down.' where name = 'Lat Pulldown';
update exercises set description = 'Stand holding dumbbells at your sides, slight bend in the elbows. Raise your arms out to shoulder height, leading with your elbows, then lower slowly. Use a lighter weight than feels natural — this movement is easy to cheat with momentum.' where name = 'Lateral Raise';
update exercises set description = 'Bar racked across the front of your shoulders, elbows up, core braced. Squat down keeping your torso as upright as possible, then drive back up. It''s more quad-dominant than a back squat, so expect to use less weight.' where name = 'Front Squat';
update exercises set description = 'Hold the bar at hip level, feet hip-width. Push your hips back while keeping a slight knee bend, lowering the bar along your legs until you feel a stretch in your hamstrings, then drive your hips forward to stand. Keep the bar close to your legs the whole way.' where name = 'Romanian Deadlift';
update exercises set description = 'Lie face down (or seated, depending on the machine) with the pad against your lower legs. Curl your heels toward your glutes, squeezing your hamstrings at the top, then lower slowly. Avoid lifting your hips off the pad to generate momentum.' where name = 'Leg Curl';

update exercises set description = 'Start in a plank with hands slightly wider than shoulders. Lower your chest to the floor keeping your body in a straight line, then press back up. Keep your core tight so your hips don''t sag.' where name = 'Push-Up';
update exercises set description = 'Place your hands on a bench, step, or sturdy elevated surface, feet on the floor. Lower your chest toward the surface and press back up. The higher the surface, the easier the movement — a good regression if a full push-up is too hard.' where name = 'Incline Push-Up';
update exercises set description = 'Lie on a flat bench holding a dumbbell in each hand at chest level, palms facing forward. Press both dumbbells up until your arms are extended, then lower with control. Keep your wrists stacked over your elbows.' where name = 'Dumbbell Bench Press';
update exercises set description = 'Lie on a flat bench holding dumbbells above your chest with a slight bend in your elbows. Lower the weights out to the sides in a wide arc until you feel a stretch across your chest, then bring them back together. Don''t let the elbows drop below shoulder level.' where name = 'Dumbbell Chest Fly';

update exercises set description = 'Hang from a bar with an overhand grip, hands slightly wider than shoulders. Pull your chin above the bar by driving your elbows down, then lower with control. Avoid kipping or swinging your legs for momentum.' where name = 'Pull-Up';
update exercises set description = 'Set a bar at hip height, lie underneath it, and grip it with hands shoulder-width apart. Keeping your body straight, pull your chest to the bar, then lower under control. Walk your feet further out to make it harder, closer in to make it easier.' where name = 'Inverted Row';
update exercises set description = 'Hinge forward from the hips holding a dumbbell in each hand, back flat. Pull the dumbbells toward your lower ribs, squeezing your shoulder blades together, then lower with control. Keep your neck neutral, not craned up.' where name = 'Dumbbell Bent Over Row';
update exercises set description = 'Lie on a bench holding one dumbbell with both hands above your chest. Lower it back behind your head in an arc until you feel a stretch in your lats, then pull it back over your chest. Keep a slight bend in your elbows throughout.' where name = 'Dumbbell Pullover';

update exercises set description = 'Start in a downward-dog position with hips high and hands on the floor. Bend your elbows to lower the top of your head toward the floor, then press back up. This targets your shoulders more than a regular push-up.' where name = 'Pike Push-Up';
update exercises set description = 'Sit or stand holding dumbbells at shoulder height, palms facing forward. Press both dumbbells overhead until your arms are extended, then lower with control. Avoid arching your lower back to get the weight up.' where name = 'Dumbbell Shoulder Press';
update exercises set description = 'Stand holding dumbbells in front of your thighs. Raise one or both arms straight in front of you to shoulder height, then lower slowly. Keep a slight bend in the elbows and avoid using momentum.' where name = 'Dumbbell Front Raise';

update exercises set description = 'Hang from a bar with an underhand (palms-facing-you) grip, hands shoulder-width apart. Pull yourself up until your chin clears the bar, then lower with control. The underhand grip works the biceps harder than a standard pull-up.' where name = 'Chin-Up';
update exercises set description = 'Stand holding dumbbells at your sides, palms facing forward. Curl the weights up toward your shoulders by bending at the elbow, then lower slowly. Keep your elbows pinned to your sides throughout.' where name = 'Dumbbell Biceps Curl';
update exercises set description = 'Stand holding dumbbells at your sides with palms facing your body (neutral grip). Curl the weights up without rotating your wrists, then lower with control. This grip shifts more work to the forearms and outer biceps.' where name = 'Dumbbell Hammer Curl';

update exercises set description = 'Get into a push-up position with your hands close together, thumbs and index fingers touching to form a diamond shape. Lower your chest to your hands, then press back up. This narrow hand position emphasizes the triceps.' where name = 'Diamond Push-Up';
update exercises set description = 'Sit on the edge of a bench with hands beside your hips, legs extended in front of you. Lower your body by bending your elbows until they reach about 90°, then press back up. Keep your elbows pointing backward, not flaring out.' where name = 'Bench Dips';
update exercises set description = 'Hold a dumbbell with both hands overhead, arms extended. Lower it behind your head by bending only at the elbows, then extend back up. Keep your upper arms still and close to your ears throughout.' where name = 'Dumbbell Triceps Extension';

update exercises set description = 'Stand with feet shoulder-width apart. Bend your hips and knees to lower down as if sitting into a chair, keeping your chest up, then drive back up through your heels. Go as low as you can while keeping your heels flat on the floor.' where name = 'Bodyweight Squat';
update exercises set description = 'Stand in a staggered stance with one foot forward and one back. Lower your back knee toward the floor by bending both knees, then push back up through your front heel. Keep your torso upright throughout.' where name = 'Split Squat';
update exercises set description = 'Lean your back against a wall and slide down until your knees are bent to about 90°, as if sitting in an invisible chair. Hold the position, keeping your back flat against the wall and thighs parallel to the floor.' where name = 'Wall Sit';
update exercises set description = 'Hold a dumbbell vertically against your chest with both hands. Squat down keeping your chest up and elbows brushing your inner knees, then drive back up. The front-loaded weight naturally keeps your torso upright.' where name = 'Dumbbell Goblet Squat';
update exercises set description = 'Hold a dumbbell in each hand at your sides. Step forward into a lunge, lowering your back knee toward the floor, then push off to bring your back foot forward into the next lunge. Keep your torso tall throughout.' where name = 'Dumbbell Walking Lunges';

update exercises set description = 'Lie on your back with knees bent and feet flat on the floor. Drive through your heels to lift your hips until your body forms a straight line from shoulders to knees, then lower with control. Squeeze your glutes at the top.' where name = 'Glute Bridge';
update exercises set description = 'Hold dumbbells in front of your thighs, feet hip-width apart. Push your hips back while keeping a slight knee bend, lowering the dumbbells along your legs until you feel a hamstring stretch, then drive your hips forward to stand.' where name = 'Dumbbell Romanian Deadlift';

update exercises set description = 'Stand with feet hip-width apart, holding onto something for balance if needed. Rise up onto the balls of your feet as high as you can, pause, then lower back down slowly. Do it on a step for a deeper stretch at the bottom.' where name = 'Standing Bodyweight Calf Raise';

update exercises set description = 'Hold a push-up position on your forearms, body in a straight line from head to heels. Keep your core braced and hips level — don''t let them sag or pike up. Hold for time.' where name = 'Plank';
update exercises set description = 'Lie on your back with knees bent, feet flat, hands lightly behind your head. Curl your shoulders off the floor toward your knees, squeezing your abs, then lower back down. Avoid pulling on your neck with your hands.' where name = 'Crunch';
update exercises set description = 'Lie on your back with knees bent and feet anchored or flat on the floor. Curl your entire torso up until you''re sitting upright, then lower back down with control. Keep the movement smooth, not jerky.' where name = 'Sit-Up';
update exercises set description = 'Start in a push-up position. Drive one knee toward your chest, then quickly switch legs, as if running in place horizontally. Keep your hips low and core tight throughout.' where name = 'Mountain Climbers';
update exercises set description = 'Sit with knees bent and lean back slightly, feet lifted or on the floor. Rotate your torso side to side, tapping the floor beside your hips each time. Keep your chest up rather than rounding your back.' where name = 'Russian Twist';
update exercises set description = 'Hang from a pull-up bar with arms fully extended. Keeping your legs straight (or knees bent for an easier version), raise them until they''re parallel to the floor, then lower with control. Avoid swinging.' where name = 'Hanging Leg Raise';

alter table exercises alter column description set not null;
